#!/bin/sh

#GADGETFS_PATH=/dev/gadget
UMTPRD_DAEMON_NAME=uMTPrd
UMTPRD_DAEMON_PATH=/usr/bin/umtprd
UMTPRD_DAEMON_OPTS=
UMTPRD_DAEMON_USER=root
MTP_PATH=/dev/ffs-mtp

case "$1" in
  start)
    echo -n "Start uMTPrd daemon :"
    #if [ ! -d "$GADGETFS_PATH" ]; then
    #  mkdir $GADGETFS_PATH
    #fi

    #mountpoint -q $GADGETFS_PATH
    #MOUNTED=$?
    #if [ "$MOUNTED" != "0" ] ; then
    #    mount -t gadgetfs gadgetfs $GADGETFS_PATH
    #fi

    if [ ! -d "$MTP_PATH" ]; then
      /usr/local/bin/umtprd-ffs.sh
    fi

    start-stop-daemon -S --background --name $UMTPRD_DAEMON_NAME \
                                      --chuid $UMTPRD_DAEMON_USER \
                                      --exec $UMTPRD_DAEMON_PATH \
                                      -- $UMTPRD_DAEMON_OPTS
    echo "DONE"
  ;;
  stop)
    echo -n "Stop uMTPrd daemon :"
    start-stop-daemon --stop --signal 3 --quiet --exec $UMTPRD_DAEMON_PATH
    echo " DONE"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
